#!/bin/sh


# Set CPU Characteristic
echo "performance" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor


# Set volume
alsactl init
amixer sset 'PCM' 100%
amixer sset 'Headphone' 100%


# Set time
#date -s '2020-01-04 11:56:30'
#hwclock -w -f /dev/rtc1 # system clock -> hardware
hwclock -s -f /dev/rtc1 # hardware -> system clock


# Enable CAN0
ip link set can0 type can bitrate 500000
ip link set can0 up


# Run Xorg
su root -l -c "/usr/bin/Xorg" &


# Run app
#su root -l -c "DISPLAY=:0.0 /root/app --platform xcb" &
